import { apiRequest } from "./client";

export type BillablePosition = { supply_challan_line_id: string; challan_number: string; description: string; unit: string; contract_origin?: "ORIGINAL_LOA" | "VARIATION"; contractual_item_id?: string; eligible_dispatched_quantity: string; previously_committed_pi_quantity: string; remaining_billable_quantity: string; contractual_sales_rate?: string };
export type PiLine = { id: string; line_number: number; supply_challan_line_id?: string; description_snapshot: string; hsn_snapshot?: string; unit_snapshot: string; billable_quantity: string; sales_rate: string; discount_percent: string; taxable_amount: string; cgst_percent: string; sgst_percent: string; igst_percent: string; cgst_amount: string; sgst_amount: string; igst_amount: string; line_total: string };
export type ProformaInvoice = { id: string; pi_number: string; pi_date: string; project_id: string; business_scope: "RAILWAY" | "NON_RAILWAY"; status: string; tax_mode: string; subtotal: string; discount_amount: string; taxable_amount: string; cgst_amount: string; sgst_amount: string; igst_amount: string; round_off: string; grand_total: string; amount_in_words: string; customer_snapshot: Record<string,string>; organization_snapshot: Record<string,string>; bill_to_snapshot: Record<string,string>; ship_to_snapshot: Record<string,string>; bank_snapshot: Record<string,string>; payment_terms_snapshot?: Record<string,string>; terms_snapshot?: Record<string,string>; lines: PiLine[] };
export const listPis = (token: string) => apiRequest<ProformaInvoice[]>("/proforma-invoices", { token });
export const getPi = (token: string, id: string) => apiRequest<ProformaInvoice>(`/proforma-invoices/${id}`, { token });
export const createPi = (token: string, data: Record<string, unknown>) => apiRequest<ProformaInvoice>("/proforma-invoices", { method: "POST", token, body: JSON.stringify(data) });
export const getBillablePosition = (token: string, projectId: string) => apiRequest<BillablePosition[]>(`/billable-position?project_id=${projectId}`, { token });
export const transitionPi = (token: string, id: string, action: string, reason: string) => apiRequest<ProformaInvoice>(`/proforma-invoices/${id}/actions`, { method: "POST", token, body: JSON.stringify({ action, reason }) });
export const updatePiLine = (token: string, piId: string, lineId: string, data: Record<string, unknown>) => apiRequest<ProformaInvoice>(`/proforma-invoices/${piId}/lines/${lineId}`, { method: "PUT", token, body: JSON.stringify(data) });
