import { apiRequest } from "./client";

export type InvoiceablePosition = { proforma_invoice_line_id: string; pi_number: string; description: string; unit: string; contract_origin?: "ORIGINAL_LOA" | "VARIATION"; contractual_item_id?: string; challan_line_id?: string; eligible_pi_quantity: string; previously_invoiced_quantity: string; remaining_invoiceable_quantity: string; sales_rate: string };
export type InvoiceLine = { id: string; line_number: number; proforma_invoice_line_id: string; supply_challan_line_id?: string; loa_item_id?: string; variation_line_id?: string; description_snapshot: string; unit_snapshot: string; invoiced_quantity: string; sales_rate: string; taxable_amount: string; cgst_amount: string; sgst_amount: string; igst_amount: string; line_total: string };
export type TaxInvoice = { id: string; invoice_number: string; invoice_date: string; project_id: string; business_scope: "RAILWAY" | "NON_RAILWAY"; status: string; tax_mode: "INTRA_STATE" | "INTER_STATE"; place_of_supply_state: string; place_of_supply_state_code: string; due_date?: string; taxable_amount: string; cgst_amount: string; sgst_amount: string; igst_amount: string; grand_total: string; amount_in_words: string; customer_snapshot: Record<string,string>; organization_snapshot: Record<string,string>; organization_gst_snapshot: Record<string,string>; customer_gst_snapshot?: Record<string,string>; bill_to_snapshot: Record<string,string>; ship_to_snapshot: Record<string,string>; bank_snapshot: Record<string,string>; lines: InvoiceLine[] };
export const listInvoices = (token: string) => apiRequest<TaxInvoice[]>("/tax-invoices", { token });
export const getInvoice = (token: string, id: string) => apiRequest<TaxInvoice>(`/tax-invoices/${id}`, { token });
export const createInvoice = (token: string, data: Record<string, unknown>) => apiRequest<TaxInvoice>("/tax-invoices", { method: "POST", token, body: JSON.stringify(data) });
export const getInvoiceablePosition = (token: string, projectId: string) => apiRequest<InvoiceablePosition[]>(`/invoiceable-position?project_id=${projectId}`, { token });
export const updateInvoiceLine = (token: string, invoiceId: string, lineId: string, data: Record<string, unknown>) => apiRequest<TaxInvoice>(`/tax-invoices/${invoiceId}/lines/${lineId}`, { method: "PUT", token, body: JSON.stringify(data) });
export const transitionInvoice = (token: string, id: string, action: string, reason: string) => apiRequest<TaxInvoice>(`/tax-invoices/${id}/actions`, { method: "POST", token, body: JSON.stringify({ action, reason }) });
