"""add loa contract management

Revision ID: 09d2dfe5b375
Revises: 7d8acec0b727
Create Date: 2026-08-24 01:35:30.973246
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "09d2dfe5b375"
down_revision: Union[str, Sequence[str], None] = "7d8acec0b727"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loa_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("loa_id", sa.Uuid(), nullable=False),
        sa.Column("item_number", sa.String(length=50), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("hsn_code_id", sa.Uuid(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("original_approved_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("contractual_rate", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("original_line_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("contractual_rate >= 0", name="ck_loa_item_rate"),
        sa.CheckConstraint("original_approved_quantity >= 0", name="ck_loa_item_quantity"),
        sa.CheckConstraint("original_line_value >= 0", name="ck_loa_item_value"),
        sa.ForeignKeyConstraint(
            ["hsn_code_id"],
            ["hsn_codes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loa_id"],
            ["loas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units_of_measure.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("loa_id", "item_number", name="uq_loa_item_number"),
    )
    op.create_index("ix_loa_items_loa", "loa_items", ["loa_id"], unique=False)
    op.create_table(
        "loa_variations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("loa_id", sa.Uuid(), nullable=False),
        sa.Column("reference_number", sa.String(length=100), nullable=False),
        sa.Column("variation_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("remarks", sa.String(length=2000), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','APPROVED','APPLIED','REJECTED','CANCELLED')",
            name="ck_loa_variation_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loa_id"],
            ["loas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("loa_id", "reference_number", name="uq_loa_variation_reference"),
    )
    op.create_index("ix_loa_variations_loa", "loa_variations", ["loa_id"], unique=False)
    op.create_table(
        "loa_variation_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("variation_id", sa.Uuid(), nullable=False),
        sa.Column("loa_item_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("line_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.CheckConstraint("direction IN ('POSITIVE','NEGATIVE')", name="ck_variation_direction"),
        sa.CheckConstraint("line_value >= 0", name="ck_variation_value"),
        sa.CheckConstraint("quantity > 0", name="ck_variation_quantity"),
        sa.CheckConstraint("rate >= 0", name="ck_variation_rate"),
        sa.ForeignKeyConstraint(
            ["loa_item_id"],
            ["loa_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units_of_measure.id"],
        ),
        sa.ForeignKeyConstraint(["variation_id"], ["loa_variations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_variation_lines_item", "loa_variation_lines", ["loa_item_id"], unique=False)
    op.add_column("loas", sa.Column("issuing_party_id", sa.Uuid(), nullable=True))
    op.add_column("loas", sa.Column("railway_division_id", sa.Uuid(), nullable=True))
    op.add_column(
        "loas",
        sa.Column(
            "original_contract_value",
            sa.Numeric(precision=18, scale=2),
            server_default="0.00",
            nullable=False,
        ),
    )
    op.add_column("loas", sa.Column("validity_date", sa.Date(), nullable=True))
    op.add_column("loas", sa.Column("completion_date", sa.Date(), nullable=True))
    op.add_column("loas", sa.Column("remarks", sa.String(length=2000), nullable=True))
    op.create_foreign_key(
        "fk_loas_issuing_party", "loas", "parties", ["issuing_party_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_loas_railway_division",
        "loas",
        "railway_divisions",
        ["railway_division_id"],
        ["id"],
    )
    op.add_column("projects", sa.Column("work_reference", sa.String(length=255), nullable=True))
    op.add_column("projects", sa.Column("railway_zone_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_projects_railway_zone", "projects", "railway_zones", ["railway_zone_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_projects_railway_zone", "projects", type_="foreignkey")
    op.drop_column("projects", "railway_zone_id")
    op.drop_column("projects", "work_reference")
    op.drop_constraint("fk_loas_railway_division", "loas", type_="foreignkey")
    op.drop_constraint("fk_loas_issuing_party", "loas", type_="foreignkey")
    op.drop_column("loas", "remarks")
    op.drop_column("loas", "completion_date")
    op.drop_column("loas", "validity_date")
    op.drop_column("loas", "original_contract_value")
    op.drop_column("loas", "railway_division_id")
    op.drop_column("loas", "issuing_party_id")
    op.drop_index("ix_variation_lines_item", table_name="loa_variation_lines")
    op.drop_table("loa_variation_lines")
    op.drop_index("ix_loa_variations_loa", table_name="loa_variations")
    op.drop_table("loa_variations")
    op.drop_index("ix_loa_items_loa", table_name="loa_items")
    op.drop_table("loa_items")
    # ### end Alembic commands ###
