"""add procurement and purchase orders

Revision ID: 4402ae9a6408
Revises: 6e744de45287
Create Date: 2026-08-24 02:05:36.398348
"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "4402ae9a6408"
down_revision: Union[str, Sequence[str], None] = "6e744de45287"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "numbering_series",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("prefix", sa.String(length=20), nullable=False),
        sa.Column("next_number", sa.Integer(), nullable=False),
        sa.Column("padding", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_type"),
    )
    numbering_series = sa.table(
        "numbering_series",
        sa.column("id", sa.Uuid()),
        sa.column("document_type", sa.String()),
        sa.column("prefix", sa.String()),
        sa.column("next_number", sa.Integer()),
        sa.column("padding", sa.Integer()),
    )
    op.bulk_insert(
        numbering_series,
        [
            {
                "id": uuid.uuid4(),
                "document_type": "PROCUREMENT_REQUIREMENT",
                "prefix": "PR-",
                "next_number": 1,
                "padding": 6,
            },
            {
                "id": uuid.uuid4(),
                "document_type": "PURCHASE_ORDER",
                "prefix": "PO-",
                "next_number": 1,
                "padding": 6,
            },
        ],
    )
    op.create_table(
        "procurement_requirements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requirement_number", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("loa_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_date", sa.Date(), nullable=False),
        sa.Column("required_by_date", sa.Date(), nullable=True),
        sa.Column("remarks", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED','CANCELLED')",
            name="ck_procurement_requirement_status",
        ),
        sa.ForeignKeyConstraint(
            ["loa_id"],
            ["loas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requirement_number"),
    )
    op.create_index(
        "ix_procurement_requirements_project",
        "procurement_requirements",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("po_number", sa.String(length=50), nullable=False),
        sa.Column("po_date", sa.Date(), nullable=False),
        sa.Column("vendor_party_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("loa_id", sa.Uuid(), nullable=True),
        sa.Column("procurement_requirement_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("billing_organization_address_id", sa.Uuid(), nullable=False),
        sa.Column("ship_to_organization_address_id", sa.Uuid(), nullable=True),
        sa.Column("ship_to_party_address_id", sa.Uuid(), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("payment_term_id", sa.Uuid(), nullable=True),
        sa.Column("terms_version_id", sa.Uuid(), nullable=True),
        sa.Column("tax_mode", sa.String(length=20), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("terms_override_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="DRAFT", nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("vendor_snapshot", sa.JSON(), nullable=False),
        sa.Column("organization_snapshot", sa.JSON(), nullable=False),
        sa.Column("billing_address_snapshot", sa.JSON(), nullable=False),
        sa.Column("shipping_address_snapshot", sa.JSON(), nullable=False),
        sa.Column("payment_terms_snapshot", sa.JSON(), nullable=True),
        sa.Column("terms_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','SUBMITTED','APPROVED','ISSUED',"
            "'PARTIALLY_FULFILLED','FULFILLED','REJECTED','CANCELLED')",
            name="ck_purchase_order_status",
        ),
        sa.CheckConstraint(
            "tax_mode IN ('INTRA_STATE','INTER_STATE')", name="ck_purchase_order_tax_mode"
        ),
        sa.CheckConstraint(
            "(ship_to_organization_address_id IS NOT NULL) <> "
            "(ship_to_party_address_id IS NOT NULL)",
            name="ck_purchase_order_single_ship_to",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["billing_organization_address_id"],
            ["organization_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loa_id"],
            ["loas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_term_id"],
            ["payment_terms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["procurement_requirement_id"],
            ["procurement_requirements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_to_organization_address_id"],
            ["organization_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_to_party_address_id"],
            ["party_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["terms_version_id"],
            ["terms_condition_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_party_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("po_number"),
    )
    op.create_index("ix_purchase_orders_loa", "purchase_orders", ["loa_id"], unique=False)
    op.create_index("ix_purchase_orders_project", "purchase_orders", ["project_id"], unique=False)
    op.create_table(
        "procurement_requirement_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("product_model_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("hsn_code_id", sa.Uuid(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("required_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("loa_item_id", sa.Uuid(), nullable=True),
        sa.Column("variation_line_id", sa.Uuid(), nullable=True),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "NOT (loa_item_id IS NOT NULL AND variation_line_id IS NOT NULL)",
            name="ck_procurement_requirement_single_contract_source",
        ),
        sa.CheckConstraint(
            "required_quantity > 0", name="ck_procurement_requirement_line_quantity"
        ),
        sa.ForeignKeyConstraint(
            ["hsn_code_id"],
            ["hsn_codes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loa_item_id"],
            ["loa_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_model_id"],
            ["product_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"], ["procurement_requirements.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units_of_measure.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variation_line_id"],
            ["loa_variation_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_procurement_requirement_lines_requirement",
        "procurement_requirement_lines",
        ["requirement_id"],
        unique=False,
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("requirement_line_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("product_model_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("hsn_code", sa.String(length=20), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("unit_snapshot", sa.String(length=100), nullable=False),
        sa.Column("ordered_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_rate", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cgst_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("sgst_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("igst_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("loa_item_id", sa.Uuid(), nullable=True),
        sa.Column("variation_line_id", sa.Uuid(), nullable=True),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "NOT (loa_item_id IS NOT NULL AND variation_line_id IS NOT NULL)",
            name="ck_purchase_order_line_single_contract_source",
        ),
        sa.CheckConstraint("ordered_quantity > 0", name="ck_purchase_order_line_quantity"),
        sa.CheckConstraint(
            "unit_rate >= 0 AND discount_percent >= 0 AND discount_percent <= 100",
            name="ck_purchase_order_line_rates",
        ),
        sa.ForeignKeyConstraint(
            ["loa_item_id"],
            ["loa_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_model_id"],
            ["product_models.id"],
        ),
        sa.ForeignKeyConstraint(["purchase_order_id"], ["purchase_orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["requirement_line_id"],
            ["procurement_requirement_lines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units_of_measure.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variation_line_id"],
            ["loa_variation_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "purchase_order_id", "line_number", name="uq_purchase_order_line_number"
        ),
    )
    op.create_index(
        "ix_purchase_order_lines_contract",
        "purchase_order_lines",
        ["loa_item_id", "variation_line_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_purchase_order_lines_contract", table_name="purchase_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_index(
        "ix_procurement_requirement_lines_requirement", table_name="procurement_requirement_lines"
    )
    op.drop_table("procurement_requirement_lines")
    op.drop_index("ix_purchase_orders_project", table_name="purchase_orders")
    op.drop_index("ix_purchase_orders_loa", table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index("ix_procurement_requirements_project", table_name="procurement_requirements")
    op.drop_table("procurement_requirements")
    op.drop_table("numbering_series")
    # ### end Alembic commands ###
