"""add quotation management

Revision ID: 555bdb93d194
Revises: 7bb2ae2655b1
Create Date: 2026-08-24 04:17:16.532376
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "555bdb93d194"
down_revision: Union[str, Sequence[str], None] = "7bb2ae2655b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quotation_number", sa.String(length=50), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("previous_revision_id", sa.Uuid(), nullable=True),
        sa.Column("is_latest", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("quotation_date", sa.Date(), nullable=False),
        sa.Column("validity_date", sa.Date(), nullable=True),
        sa.Column("customer_party_id", sa.Uuid(), nullable=False),
        sa.Column("business_scope", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("loa_id", sa.Uuid(), nullable=True),
        sa.Column("railway_zone_id", sa.Uuid(), nullable=True),
        sa.Column("railway_division_id", sa.Uuid(), nullable=True),
        sa.Column("railway_authority_id", sa.Uuid(), nullable=True),
        sa.Column("bill_to_party_address_id", sa.Uuid(), nullable=True),
        sa.Column("bill_to_railway_address_id", sa.Uuid(), nullable=True),
        sa.Column("ship_to_party_address_id", sa.Uuid(), nullable=True),
        sa.Column("ship_to_railway_address_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("gst_registration_id", sa.Uuid(), nullable=False),
        sa.Column("payment_term_id", sa.Uuid(), nullable=True),
        sa.Column("terms_version_id", sa.Uuid(), nullable=True),
        sa.Column("enquiry_reference", sa.String(length=255), nullable=True),
        sa.Column("enquiry_date", sa.Date(), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("tax_mode", sa.String(length=20), nullable=False),
        sa.Column("place_of_supply_state", sa.String(length=100), nullable=False),
        sa.Column("place_of_supply_state_code", sa.String(length=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("amount_in_words", sa.String(length=1000), nullable=False),
        sa.Column("organization_snapshot", sa.JSON(), nullable=False),
        sa.Column("organization_gst_snapshot", sa.JSON(), nullable=False),
        sa.Column("customer_snapshot", sa.JSON(), nullable=False),
        sa.Column("customer_gst_snapshot", sa.JSON(), nullable=True),
        sa.Column("zone_snapshot", sa.JSON(), nullable=True),
        sa.Column("division_snapshot", sa.JSON(), nullable=True),
        sa.Column("authority_snapshot", sa.JSON(), nullable=True),
        sa.Column("bill_to_snapshot", sa.JSON(), nullable=False),
        sa.Column("ship_to_snapshot", sa.JSON(), nullable=True),
        sa.Column("place_of_supply_snapshot", sa.JSON(), nullable=False),
        sa.Column("payment_terms_snapshot", sa.JSON(), nullable=True),
        sa.Column("terms_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "business_scope IN ('RAILWAY','NON_RAILWAY')", name="ck_quotation_scope"
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','SUBMITTED','APPROVED','ISSUED','ACCEPTED',"
            "'REJECTED','EXPIRED','CANCELLED')",
            name="ck_quotation_status",
        ),
        sa.CheckConstraint(
            "tax_mode IN ('INTRA_STATE','INTER_STATE')", name="ck_quotation_tax_mode"
        ),
        sa.CheckConstraint("revision_number >= 0", name="ck_quotation_revision"),
        sa.CheckConstraint(
            "validity_date IS NULL OR validity_date >= quotation_date", name="ck_quotation_validity"
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bill_to_party_address_id"],
            ["party_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bill_to_railway_address_id"],
            ["railway_authority_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_party_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gst_registration_id"],
            ["gst_registrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loa_id"],
            ["loas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_term_id"],
            ["payment_terms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_revision_id"],
            ["quotations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["railway_authority_id"],
            ["railway_authorities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["railway_division_id"],
            ["railway_divisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["railway_zone_id"],
            ["railway_zones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_to_party_address_id"],
            ["party_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_to_railway_address_id"],
            ["railway_authority_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["terms_version_id"],
            ["terms_condition_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quotation_number", "revision_number", name="uq_quotation_revision"),
    )
    op.create_index("ix_quotations_customer", "quotations", ["customer_party_id"], unique=False)
    op.create_index(
        "ix_quotations_number_latest", "quotations", ["quotation_number", "is_latest"], unique=False
    )
    op.create_index("ix_quotations_project", "quotations", ["project_id"], unique=False)
    op.create_table(
        "quotation_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quotation_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("product_model_id", sa.Uuid(), nullable=True),
        sa.Column("oem_party_id", sa.Uuid(), nullable=True),
        sa.Column("description_snapshot", sa.String(length=2000), nullable=False),
        sa.Column("oem_snapshot", sa.String(length=255), nullable=True),
        sa.Column("model_snapshot", sa.String(length=255), nullable=True),
        sa.Column("hsn_snapshot", sa.String(length=20), nullable=True),
        sa.Column("unit_snapshot", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quoted_rate", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cgst_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("sgst_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("igst_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.CheckConstraint("quantity > 0", name="ck_quotation_line_quantity"),
        sa.CheckConstraint("quoted_rate >= 0", name="ck_quotation_line_rate"),
        sa.ForeignKeyConstraint(
            ["oem_party_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_model_id"],
            ["product_models.id"],
        ),
        sa.ForeignKeyConstraint(["quotation_id"], ["quotations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quotation_id", "line_number", name="uq_quotation_line_number"),
    )
    op.execute(
        "INSERT INTO numbering_series "
        "(id, document_type, prefix, next_number, padding, updated_at) "
        "VALUES (gen_random_uuid(), 'QUOTATION', 'QTN-', 1, 6, now()) "
        "ON CONFLICT (document_type) DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM numbering_series WHERE document_type = 'QUOTATION'")
    op.drop_table("quotation_lines")
    op.drop_index("ix_quotations_project", table_name="quotations")
    op.drop_index("ix_quotations_number_latest", table_name="quotations")
    op.drop_index("ix_quotations_customer", table_name="quotations")
    op.drop_table("quotations")
    # ### end Alembic commands ###
