"""add tax invoices and billing

Revision ID: 7bb2ae2655b1
Revises: 2184131cfc8a
Create Date: 2026-08-24 03:42:42.437753
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "7bb2ae2655b1"
down_revision: Union[str, Sequence[str], None] = "2184131cfc8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tax_invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("loa_id", sa.Uuid(), nullable=True),
        sa.Column("customer_party_id", sa.Uuid(), nullable=False),
        sa.Column("business_scope", sa.String(length=20), nullable=False),
        sa.Column("railway_division_id", sa.Uuid(), nullable=True),
        sa.Column("railway_authority_id", sa.Uuid(), nullable=True),
        sa.Column("bill_to_party_address_id", sa.Uuid(), nullable=True),
        sa.Column("bill_to_railway_address_id", sa.Uuid(), nullable=True),
        sa.Column("ship_to_party_address_id", sa.Uuid(), nullable=True),
        sa.Column("ship_to_railway_address_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("gst_registration_id", sa.Uuid(), nullable=False),
        sa.Column("bank_account_id", sa.Uuid(), nullable=False),
        sa.Column("payment_term_id", sa.Uuid(), nullable=True),
        sa.Column("terms_version_id", sa.Uuid(), nullable=True),
        sa.Column("tax_mode", sa.String(length=20), nullable=False),
        sa.Column("place_of_supply_state", sa.String(length=100), nullable=False),
        sa.Column("place_of_supply_state_code", sa.String(length=2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("amount_in_words", sa.String(length=1000), nullable=False),
        sa.Column("organization_snapshot", sa.JSON(), nullable=False),
        sa.Column("organization_gst_snapshot", sa.JSON(), nullable=False),
        sa.Column("customer_snapshot", sa.JSON(), nullable=False),
        sa.Column("customer_gst_snapshot", sa.JSON(), nullable=True),
        sa.Column("division_snapshot", sa.JSON(), nullable=True),
        sa.Column("authority_snapshot", sa.JSON(), nullable=True),
        sa.Column("bill_to_snapshot", sa.JSON(), nullable=False),
        sa.Column("ship_to_snapshot", sa.JSON(), nullable=False),
        sa.Column("place_of_supply_snapshot", sa.JSON(), nullable=False),
        sa.Column("bank_snapshot", sa.JSON(), nullable=False),
        sa.Column("payment_terms_snapshot", sa.JSON(), nullable=True),
        sa.Column("terms_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "business_scope IN ('RAILWAY','NON_RAILWAY')", name="ck_invoice_business_scope"
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','SUBMITTED','APPROVED','ISSUED','CANCELLED')",
            name="ck_invoice_status",
        ),
        sa.CheckConstraint("tax_mode IN ('INTRA_STATE','INTER_STATE')", name="ck_invoice_tax_mode"),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bill_to_party_address_id"],
            ["party_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bill_to_railway_address_id"],
            ["railway_authority_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_party_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gst_registration_id"],
            ["gst_registrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loa_id"],
            ["loas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_term_id"],
            ["payment_terms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["railway_authority_id"],
            ["railway_authorities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["railway_division_id"],
            ["railway_divisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_to_party_address_id"],
            ["party_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_to_railway_address_id"],
            ["railway_authority_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["terms_version_id"],
            ["terms_condition_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_number"),
    )
    op.create_index("ix_tax_invoices_loa", "tax_invoices", ["loa_id"], unique=False)
    op.create_index("ix_tax_invoices_project", "tax_invoices", ["project_id"], unique=False)
    op.create_table(
        "tax_invoice_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tax_invoice_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("proforma_invoice_line_id", sa.Uuid(), nullable=False),
        sa.Column("supply_challan_line_id", sa.Uuid(), nullable=True),
        sa.Column("loa_item_id", sa.Uuid(), nullable=True),
        sa.Column("variation_line_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("description_snapshot", sa.String(length=2000), nullable=False),
        sa.Column("hsn_snapshot", sa.String(length=20), nullable=True),
        sa.Column("unit_snapshot", sa.String(length=100), nullable=False),
        sa.Column("invoiced_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sales_rate", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cgst_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("sgst_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("igst_percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "NOT (loa_item_id IS NOT NULL AND variation_line_id IS NOT NULL)",
            name="ck_tax_invoice_line_single_contract_source",
        ),
        sa.CheckConstraint("invoiced_quantity > 0", name="ck_tax_invoice_line_quantity"),
        sa.CheckConstraint("sales_rate >= 0", name="ck_tax_invoice_line_rate"),
        sa.ForeignKeyConstraint(
            ["loa_item_id"],
            ["loa_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proforma_invoice_line_id"],
            ["proforma_invoice_lines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supply_challan_line_id"],
            ["supply_challan_lines.id"],
        ),
        sa.ForeignKeyConstraint(["tax_invoice_id"], ["tax_invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["variation_line_id"],
            ["loa_variation_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tax_invoice_id", "line_number", name="uq_tax_invoice_line_number"),
    )
    op.create_index(
        "ix_tax_invoice_lines_challan_line",
        "tax_invoice_lines",
        ["supply_challan_line_id"],
        unique=False,
    )
    op.create_index(
        "ix_tax_invoice_lines_pi_line",
        "tax_invoice_lines",
        ["proforma_invoice_line_id"],
        unique=False,
    )
    op.execute(
        "INSERT INTO numbering_series "
        "(id, document_type, prefix, next_number, padding, updated_at) "
        "VALUES (gen_random_uuid(), 'TAX_INVOICE', 'INV-', 1, 6, now()) "
        "ON CONFLICT (document_type) DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM numbering_series WHERE document_type = 'TAX_INVOICE'")
    op.drop_index("ix_tax_invoice_lines_pi_line", table_name="tax_invoice_lines")
    op.drop_index("ix_tax_invoice_lines_challan_line", table_name="tax_invoice_lines")
    op.drop_table("tax_invoice_lines")
    op.drop_index("ix_tax_invoices_project", table_name="tax_invoices")
    op.drop_index("ix_tax_invoices_loa", table_name="tax_invoices")
    op.drop_table("tax_invoices")
    # ### end Alembic commands ###
