"""add supply challans and dispatch

Revision ID: c5133497fa43
Revises: d629cbea6e51
Create Date: 2026-08-24 02:55:18.652110
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c5133497fa43"
down_revision: str | Sequence[str] | None = "d629cbea6e51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supply_challans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("challan_number", sa.String(length=50), nullable=False),
        sa.Column("challan_date", sa.Date(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("loa_id", sa.Uuid(), nullable=True),
        sa.Column("business_scope", sa.String(length=20), nullable=False),
        sa.Column("customer_party_id", sa.Uuid(), nullable=False),
        sa.Column("railway_division_id", sa.Uuid(), nullable=True),
        sa.Column("consignee_authority_id", sa.Uuid(), nullable=True),
        sa.Column("bill_to_authority_id", sa.Uuid(), nullable=True),
        sa.Column("ship_to_railway_address_id", sa.Uuid(), nullable=True),
        sa.Column("ship_to_party_address_id", sa.Uuid(), nullable=True),
        sa.Column("dispatch_from_address_id", sa.Uuid(), nullable=False),
        sa.Column("transporter", sa.String(length=255), nullable=True),
        sa.Column("vehicle_number", sa.String(length=50), nullable=True),
        sa.Column("transport_reference", sa.String(length=255), nullable=True),
        sa.Column("eway_bill_reference", sa.String(length=255), nullable=True),
        sa.Column("delivery_notes", sa.Text(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("customer_snapshot", sa.JSON(), nullable=False),
        sa.Column("division_snapshot", sa.JSON(), nullable=True),
        sa.Column("consignee_snapshot", sa.JSON(), nullable=True),
        sa.Column("delivery_address_snapshot", sa.JSON(), nullable=False),
        sa.Column("dispatch_from_snapshot", sa.JSON(), nullable=False),
        sa.Column("organization_snapshot", sa.JSON(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_date", sa.Date(), nullable=True),
        sa.Column("receiving_authority_text", sa.String(length=255), nullable=True),
        sa.Column("acknowledgement_reference", sa.String(length=255), nullable=True),
        sa.Column("acknowledgement_remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "business_scope IN ('RAILWAY','NON_RAILWAY')", name="ck_challan_business_scope"
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','READY','DISPATCHED','DELIVERED','ACKNOWLEDGED','CANCELLED')",
            name="ck_challan_status",
        ),
        sa.ForeignKeyConstraint(
            ["bill_to_authority_id"],
            ["railway_authorities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consignee_authority_id"],
            ["railway_authorities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_party_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dispatch_from_address_id"],
            ["organization_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loa_id"],
            ["loas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["railway_division_id"],
            ["railway_divisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_to_party_address_id"],
            ["party_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_to_railway_address_id"],
            ["railway_authority_addresses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("challan_number"),
    )
    op.create_index("ix_supply_challans_loa", "supply_challans", ["loa_id"], unique=False)
    op.create_index("ix_supply_challans_project", "supply_challans", ["project_id"], unique=False)
    op.create_table(
        "supply_challan_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supply_challan_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("loa_item_id", sa.Uuid(), nullable=True),
        sa.Column("variation_line_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("description_snapshot", sa.String(length=2000), nullable=False),
        sa.Column("hsn_snapshot", sa.String(length=20), nullable=True),
        sa.Column("unit_snapshot", sa.String(length=100), nullable=False),
        sa.Column("dispatched_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "NOT (loa_item_id IS NOT NULL AND variation_line_id IS NOT NULL)",
            name="ck_challan_line_single_contract_source",
        ),
        sa.CheckConstraint("dispatched_quantity > 0", name="ck_challan_line_quantity"),
        sa.ForeignKeyConstraint(
            ["loa_item_id"],
            ["loa_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(["supply_challan_id"], ["supply_challans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["variation_line_id"],
            ["loa_variation_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supply_challan_id", "line_number", name="uq_challan_line_number"),
    )
    op.create_index(
        "ix_challan_lines_contract",
        "supply_challan_lines",
        ["loa_item_id", "variation_line_id"],
        unique=False,
    )
    op.create_table(
        "challan_receipt_allocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("challan_line_id", sa.Uuid(), nullable=False),
        sa.Column("material_receipt_line_id", sa.Uuid(), nullable=False),
        sa.Column("allocated_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.CheckConstraint("allocated_quantity > 0", name="ck_challan_allocation_quantity"),
        sa.ForeignKeyConstraint(
            ["challan_line_id"], ["supply_challan_lines.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["material_receipt_line_id"],
            ["material_receipt_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "challan_line_id", "material_receipt_line_id", name="uq_challan_receipt_allocation"
        ),
    )
    op.create_index(
        "ix_challan_allocations_receipt_line",
        "challan_receipt_allocations",
        ["material_receipt_line_id"],
        unique=False,
    )
    op.execute(
        "INSERT INTO numbering_series "
        "(id, document_type, prefix, next_number, padding, updated_at) "
        "VALUES (gen_random_uuid(), 'SUPPLY_CHALLAN', 'CH-', 1, 6, now()) "
        "ON CONFLICT (document_type) DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM numbering_series WHERE document_type = 'SUPPLY_CHALLAN'")
    op.drop_index("ix_challan_allocations_receipt_line", table_name="challan_receipt_allocations")
    op.drop_table("challan_receipt_allocations")
    op.drop_index("ix_challan_lines_contract", table_name="supply_challan_lines")
    op.drop_table("supply_challan_lines")
    op.drop_index("ix_supply_challans_project", table_name="supply_challans")
    op.drop_index("ix_supply_challans_loa", table_name="supply_challans")
    op.drop_table("supply_challans")
    # ### end Alembic commands ###
