"""add material receipts

Revision ID: d629cbea6e51
Revises: 4402ae9a6408
Create Date: 2026-08-24 02:37:06.048187
"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "d629cbea6e51"
down_revision: Union[str, Sequence[str], None] = "4402ae9a6408"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_number", sa.String(length=50), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_party_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("loa_id", sa.Uuid(), nullable=True),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column("vendor_invoice_reference", sa.String(length=255), nullable=True),
        sa.Column("delivery_reference", sa.String(length=255), nullable=True),
        sa.Column("receiving_location", sa.String(length=255), nullable=False),
        sa.Column("received_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remarks", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("po_number_snapshot", sa.String(length=50), nullable=False),
        sa.Column("vendor_snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','RECEIVED','VERIFIED','CANCELLED')",
            name="ck_material_receipt_status",
        ),
        sa.ForeignKeyConstraint(
            ["loa_id"],
            ["loas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["received_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_party_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_number"),
    )
    op.create_index(
        "ix_material_receipts_po", "material_receipts", ["purchase_order_id"], unique=False
    )
    op.create_table(
        "material_receipt_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("material_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_line_id", sa.Uuid(), nullable=False),
        sa.Column("ordered_quantity_snapshot", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "previously_accepted_snapshot", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column("quantity_received", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quantity_accepted", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quantity_short", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quantity_damaged", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quantity_rejected", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quantity_excess", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("description_snapshot", sa.String(length=2000), nullable=False),
        sa.Column("unit_snapshot", sa.String(length=100), nullable=False),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "quantity_received = quantity_accepted + quantity_damaged + quantity_rejected",
            name="ck_receipt_line_physical_total",
        ),
        sa.CheckConstraint(
            "quantity_received >= 0 AND quantity_accepted >= 0 AND quantity_short >= 0 AND "
            "quantity_damaged >= 0 AND quantity_rejected >= 0 AND quantity_excess >= 0",
            name="ck_receipt_line_quantities",
        ),
        sa.ForeignKeyConstraint(
            ["material_receipt_id"], ["material_receipts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_line_id"],
            ["purchase_order_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "material_receipt_id", "purchase_order_line_id", name="uq_receipt_po_line"
        ),
    )
    op.create_index(
        "ix_material_receipt_lines_po_line",
        "material_receipt_lines",
        ["purchase_order_line_id"],
        unique=False,
    )
    numbering_series = sa.table(
        "numbering_series",
        sa.column("id", sa.Uuid()),
        sa.column("document_type", sa.String()),
        sa.column("prefix", sa.String()),
        sa.column("next_number", sa.Integer()),
        sa.column("padding", sa.Integer()),
    )
    op.bulk_insert(
        numbering_series,
        [
            {
                "id": uuid.uuid4(),
                "document_type": "MATERIAL_RECEIPT",
                "prefix": "GRN-",
                "next_number": 1,
                "padding": 6,
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_material_receipt_lines_po_line", table_name="material_receipt_lines")
    op.drop_table("material_receipt_lines")
    op.drop_index("ix_material_receipts_po", table_name="material_receipts")
    op.drop_table("material_receipts")
    op.execute("DELETE FROM numbering_series WHERE document_type = 'MATERIAL_RECEIPT'")
    # ### end Alembic commands ###
