import { useCallback,useEffect,useState } from "react";
import { alertAction,evaluateAlerts,listAlerts,listRules,updateRule,type Alert,type AlertRule } from "../api/attention";
import { useAuth } from "../auth/AuthContext";
import { Icon } from "../components/Icon";

export function AlertsPage(){const {token,user}=useAuth();const [alerts,setAlerts]=useState<Alert[]>([]);const [rules,setRules]=useState<AlertRule[]>([]);const [status,setStatus]=useState("");const superAdmin=user?.roles.some(r=>r.name==="SUPER-ADMIN");const load=useCallback(async()=>{if(!token)return;setAlerts(await listAlerts(token,status));if(superAdmin)setRules(await listRules(token));},[token,status,superAdmin]);useEffect(()=>{void load();},[load]);async function act(id:string,action:string){if(token){await alertAction(token,id,action,action==="ACKNOWLEDGE"?undefined:`${action} from Alerts`);await load();}}return <section className="alerts-page page-stack">
  <header className="page-heading"><p>MY ATTENTION</p><h1>Alerts</h1></header>
  <section className="wcdms-card alert-controls" aria-label="Alert filters and actions"><label><span>Alert status</span><select aria-label="Alert status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>OPEN</option><option>ACKNOWLEDGED</option><option>RESOLVED</option></select></label>{superAdmin&&<button className="button-secondary" onClick={()=>token&&void evaluateAlerts(token).then(load)}>Evaluate alerts</button>}</section>
  <section className="wcdms-card active-alerts"><h2>Active Alerts</h2>{alerts.length===0?<div className="contained-empty success-empty"><span>✓</span><p>No alerts require attention.</p></div>:<div className="alert-list">{alerts.map(a=><article key={a.id}><header><strong><span className={`severity-dot ${a.severity.toLowerCase()}`}/>{a.severity} — {a.title}</strong><span className={`status-badge ${a.status.toLowerCase()}`}>{a.status}</span></header><p>{a.message}</p><small>Source: {a.source_entity_type} · Triggered {new Date(a.triggered_at).toLocaleDateString()}{a.due_date?` · Target ${a.due_date}`:""}</small><div className="alert-actions">{a.status==="OPEN"&&<button onClick={()=>void act(a.id,"ACKNOWLEDGE")}>Acknowledge</button>}{superAdmin&&["OPEN","ACKNOWLEDGED"].includes(a.status)&&<><button onClick={()=>void act(a.id,"RESOLVE")}>Resolve</button><button className="button-danger" onClick={()=>void act(a.id,"DISMISS")}>Dismiss</button></>}</div></article>)}</div>}</section>
  {superAdmin&&<section className="wcdms-card alert-rules"><h2>Alert Rule Settings</h2>{rules.length===0?<div className="contained-empty"><Icon name="bell"/><p>No alert rules are configured.</p></div>:<div className="table-container"><table><thead><tr><th>Alert Rule</th><th>Severity</th><th>Trigger</th><th>Trigger Value</th><th>Status</th><th>Action</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td>{r.rule_type}</td><td><span className={`severity-dot ${r.severity.toLowerCase()}`}/>{r.severity}</td><td>{r.warning_days===null?"event":"days"}</td><td>{r.warning_days??"—"}</td><td><span className={`status-badge ${r.is_enabled?"enabled":"disabled"}`}>{r.is_enabled?"Enabled":"Disabled"}</span></td><td><button className="table-action" onClick={()=>token&&void updateRule(token,r.id,{is_enabled:!r.is_enabled}).then(load)}>{r.is_enabled?"Disable":"Enable"}</button></td></tr>)}</tbody></table></div>}</section>}
</section>}
