import { FormEvent, useCallback, useEffect, useState } from "react";
import { acknowledgeChallan, getChallan, transitionChallan, updateChallanLine, type ChallanLine, type SupplyChallan } from "../api/dispatch";
import { useAuth } from "../auth/AuthContext";
import { useParams } from "react-router-dom";

export function ChallanDetailPage() {
  const { challanId = "" } = useParams(); const { token, user } = useAuth();
  const [challan, setChallan] = useState<SupplyChallan | null>(null);
  const load = useCallback(async () => { if (token) setChallan(await getChallan(token, challanId)); }, [token, challanId]);
  useEffect(() => { void load(); }, [load]);
  async function act(action: string) { if (token) { await transitionChallan(token, challanId, action, `${action} from Challan detail`); await load(); } }
  async function acknowledge(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token) return; const data = new FormData(event.currentTarget); await acknowledgeChallan(token, challanId, { acknowledged_date: data.get("date"), receiving_authority_text: data.get("authority"), acknowledgement_reference: data.get("reference") || undefined }); await load(); }
  async function editLine(event: FormEvent<HTMLFormElement>, line: ChallanLine) { event.preventDefault(); if (!token || line.allocations.length !== 1) return; const data = new FormData(event.currentTarget); const quantity = data.get("quantity"); await updateChallanLine(token, challanId, line.id, { dispatched_quantity: quantity, allocations: [{ material_receipt_line_id: line.allocations[0].material_receipt_line_id, allocated_quantity: quantity }] }); await load(); }
  const superAdmin = user?.roles.some((role) => role.name === "SUPER-ADMIN");
  return <section className="space-y-6"><h1 className="text-3xl font-semibold">{challan?.challan_number ?? "Supply Challan"}</h1><p>Status: <strong>{challan?.status}</strong></p><p>Deliver to: {challan?.consignee_snapshot?.name ?? challan?.customer_snapshot.legal_name} — {challan?.delivery_address_snapshot.address_line_1}</p><div><h2 className="text-xl">Dispatched material</h2>{challan?.lines.map((line) => <article key={line.id} className="rounded border p-3"><strong>{line.line_number}. {line.description_snapshot}</strong>{challan.status === "DRAFT" && line.allocations.length === 1 ? <form onSubmit={(event) => void editLine(event, line)} className="flex gap-2"><input name="quantity" aria-label={`Dispatch quantity line ${line.line_number}`} type="number" step="0.0001" min="0.0001" defaultValue={line.dispatched_quantity} required /><span>{line.unit_snapshot}</span><button>Save quantity</button></form> : <p>{line.dispatched_quantity} {line.unit_snapshot}</p>}</article>)}</div><div className="space-x-3">{challan?.status === "DRAFT" && <button onClick={() => void act("READY")}>Mark ready</button>}{challan?.status === "READY" && <button onClick={() => void act("DISPATCH")}>Dispatch</button>}{challan?.status === "DISPATCHED" && <button onClick={() => void act("DELIVER")}>Mark delivered</button>}{challan && ["DRAFT", "READY"].includes(challan.status) && <button onClick={() => void act("CANCEL")}>Cancel</button>}{challan && ["DISPATCHED", "DELIVERED", "ACKNOWLEDGED"].includes(challan.status) && superAdmin && <button onClick={() => void act("CANCEL")}>Protected cancel</button>}</div>{challan?.status === "DELIVERED" && <form onSubmit={acknowledge} className="grid gap-2 rounded border p-4 md:grid-cols-3"><h2 className="text-xl md:col-span-3">Record acknowledgement</h2><input name="date" type="date" aria-label="Acknowledgement date" required /><input name="authority" placeholder="Receiving authority" required /><input name="reference" placeholder="Acknowledgement reference" /><button>Record acknowledgement</button></form>}</section>;
}
