import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ApiError } from "../api/client";
import { listProjects, type Project } from "../api/contracts";
import { approveLoaImport, cancelLoaImport, getLoaImport, openOriginalLoa, resolveLoaImportMasters, retryLoaImport, saveLoaImportReview, type LoaImport, type LoaImportLine } from "../api/loaImports";
import { listMasterData, type MasterRecord } from "../api/masterData";
import { useAuth } from "../auth/AuthContext";

const display = (r: MasterRecord) => String(r.data.name ?? r.data.legal_name ?? r.data.code ?? r.id);
const field = (f: FormData, n: string) => String(f.get(n) ?? "").trim() || null;
const metric = (r: Record<string, unknown>, k: string) => Number(r[k] ?? 0);

export function LoaImportReviewPage() {
  const { token } = useAuth(); const { importId = "" } = useParams(); const navigate = useNavigate();
  const [item, setItem] = useState<LoaImport | null>(null); const [projects, setProjects] = useState<Project[]>([]);
  const [masters, setMasters] = useState<Record<string, MasterRecord[]>>({}); const [lines, setLines] = useState<LoaImportLine[]>([]);
  const [projectMode, setProjectMode] = useState<"new" | "existing">("new"); const [showBoq, setShowBoq] = useState(true); const [onlyUnresolved, setOnlyUnresolved] = useState(false);
  const [newProjectCode, setNewProjectCode] = useState("");
  const [showExtractionDetails, setShowExtractionDetails] = useState(false);
  const [refreshingMasters, setRefreshingMasters] = useState(false);
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { if (!token) return; try { const resources = ["railway-zones", "railway-divisions", "railway-authorities", "units", "hsn-codes"]; const [record, projectList, ...lists] = await Promise.all([getLoaImport(token, importId), listProjects(token), ...resources.map((resource) => listMasterData(token, resource))]); record.project_candidates ??= []; record.authority_candidates ??= []; record.boq_reconciliation ??= {}; record.lines = record.lines.map((line) => ({ ...line, extraction_outcome: line.extraction_outcome ?? "EXTRACTED" })); setItem(record); setLines(record.lines); setProjects(projectList); setMasters(Object.fromEntries(resources.map((resource, index) => [resource, lists[index].items]))); setProjectMode(record.project_id ? "existing" : "new"); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to load Railway LOA review."); } }, [importId, token]);
  useEffect(() => void load(), [load]);
  useEffect(() => {
    const trackProjectCode = (event: Event) => {
      const target = event.target;
      if (target instanceof HTMLInputElement && target.name === "new_project_code") {
        setNewProjectCode(target.value);
      }
    };
    document.addEventListener("input", trackProjectCode);
    return () => document.removeEventListener("input", trackProjectCode);
  }, []);
  useEffect(() => { if (!showBoq) { setOnlyUnresolved(false); setShowBoq(true); } }, [showBoq]);
  const unresolved = useMemo(() => lines.filter((line) => !["EXTRACTED", "EXPLICITLY_IGNORED_BY_OWNER"].includes(line.extraction_outcome ?? "EXTRACTED")), [lines]);
  const visibleLines = onlyUnresolved ? unresolved : lines;
  const updateLine = (id: string, key: keyof LoaImportLine, value: string) => setLines((current) => current.map((line) => line.id === id ? { ...line, [key]: value } : line));
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !item) return; const data = new FormData(event.currentTarget); try { const updated = await saveLoaImportReview(token, item.id, { project_id: projectMode === "existing" ? field(data, "project_id") : null, railway_zone_id: field(data, "railway_zone_id"), railway_division_id: field(data, "railway_division_id"), authority_id: field(data, "authority_id"), issuing_party_id: field(data, "issuing_party_id"), loa_number: field(data, "loa_number"), tender_reference: field(data, "tender_reference"), loa_date: field(data, "loa_date"), completion_period: field(data, "completion_period"), completion_date: field(data, "completion_date"), work_description: field(data, "work_description"), contract_value: field(data, "contract_value"), lines: lines.map((line) => ({ ...line, id: undefined, line_number: undefined })) }); setItem(updated); setLines(updated.lines); setMessage("Review draft saved."); setError(null); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to save review draft."); } }
  async function approve(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !item) return; const data = new FormData(event.currentTarget); const payload: Record<string, unknown> = { confirm_duplicate: data.get("confirm_duplicate") === "on" }; if (projectMode === "new") payload.new_project = { code: field(data, "new_project_code"), name: field(data, "new_project_name"), work_reference: item.tender_reference, customer_party_id: item.issuing_party_id, business_scope: "RAILWAY", railway_zone_id: item.railway_zone_id, railway_division_id: item.railway_division_id, status: "ACTIVE" }; try { const approved = await approveLoaImport(token, item.id, payload); if (approved.loa_id) navigate(`/loas/${approved.loa_id}`); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to approve Railway LOA import."); } }
  async function refreshMasterMatches() { if (!token || !item) return; setRefreshingMasters(true); setError(null); setMessage(null); try { const updated = await resolveLoaImportMasters(token, item.id); updated.project_candidates ??= []; updated.authority_candidates ??= []; updated.boq_reconciliation ??= {}; setItem(updated); setLines(updated.lines); setMessage("Railway Master matches refreshed."); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to refresh Railway Master matches."); } finally { setRefreshingMasters(false); } }
  if (!item) return <p>{error ?? "Loading Railway LOA review…"}</p>;
  const editable = !["APPROVED", "CANCELLED"].includes(item.status); const reconciliation = item.boq_reconciliation ?? {}; const boqIssues = item.boq_readiness_issues ?? []; const complete = Boolean(reconciliation.complete) && unresolved.length === 0 && boqIssues.length === 0; const zoneName = display((masters["railway-zones"] ?? []).find((record) => record.id === item.railway_zone_id) ?? { id: "", resource: "", data: { name: item.extracted_zone_text || "Not resolved" }, is_active: true, created_at: "", updated_at: "" }); const divisionName = display((masters["railway-divisions"] ?? []).find((record) => record.id === item.railway_division_id) ?? { id: "", resource: "", data: { name: item.extracted_division_text || "Not resolved" }, is_active: true, created_at: "", updated_at: "" }); const authorityByRole = (role: string) => item.authority_candidates.filter((candidate) => candidate.role === role); const groupContext = new Map((item.schedules ?? []).flatMap((schedule) => schedule.groups.map((group) => [group.id, { schedule: schedule.title_normalized, group: group.title_normalized }]))); const requiredActions = [!item.railway_zone_id && "Select the Railway Zone from Railway Master", !item.railway_division_id && "Select a Railway Division compatible with the Zone", !item.loa_date && "LOA Issued Date requires review", projectMode === "existing" && !item.project_id && "Select the existing Project", projectMode === "new" && !newProjectCode.trim() && "New Project code is required", ...boqIssues.map((issue) => issue.message)].filter(Boolean) as string[]; const approvalBlocked = requiredActions.length > 0;
  const unmappedAuthority = item.authority_candidates.find((candidate) => !candidate.master_id);
  return <section className="loa-import-review page-stack"><header className="page-heading"><p>RAILWAY LOA IMPORT</p><h1>{item.loa_number || item.original_filename}</h1><span className={`status-badge ${item.status.toLowerCase()}`}>{item.status.replaceAll("_", " ")}</span></header>{error && <p role="alert" className="settings-feedback error">{error}</p>}{message && <p role="status" className="settings-feedback success">{message}</p>}
    <section className="wcdms-card import-source"><h2>Source Document</h2><dl><div><dt>Original filename</dt><dd>{item.original_filename}</dd></div><div><dt>Uploaded at</dt><dd>{new Date(item.uploaded_at).toLocaleString()}</dd></div><div><dt>Extraction method</dt><dd>{item.extraction_method || "Pending"}</dd></div><div><dt>Extraction state</dt><dd>{item.status}</dd></div></dl><div className="import-actions"><button className="button-secondary" onClick={() => void openOriginalLoa(token!, item.id, item.original_filename)}>View Original LOA</button>{item.status === "EXTRACTION_FAILED" && <button className="button-primary" onClick={() => void retryLoaImport(token!, item.id).then(load)}>Retry Extraction</button>}</div></section>
    <form onSubmit={save} className="import-review-form"><section className="wcdms-card"><h2>Project handling</h2><div className="choice-row"><label className="check-field"><input type="radio" checked={projectMode === "new"} onChange={() => setProjectMode("new")} /> Create new Railway Project from this LOA</label><label className="check-field"><input type="radio" checked={projectMode === "existing"} onChange={() => setProjectMode("existing")} /> Link to existing Railway Project</label></div>{(item.project_candidates ?? []).length > 0 && <><p>Possible matches — owner confirmation required; none was silently linked.</p><ul>{item.project_candidates.map((candidate) => <li key={candidate.id}>{candidate.code} — {candidate.name}: {candidate.reason}</li>)}</ul></>}{projectMode === "existing" && <label>Existing Railway Project<select name="project_id" defaultValue={item.project_id || ""} required><option value="">Select confirmed Project</option>{projects.filter((p) => p.business_scope === "RAILWAY").map((p) => <option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></label>}</section>
      <section className="wcdms-card"><h2>Contract Details</h2><div className="settings-form"><label>LOA Number<input name="loa_number" defaultValue={item.loa_number || ""} required /></label><label>Tender / Contract Reference<input name="tender_reference" defaultValue={item.tender_reference || ""} /></label><label>LOA Issued Date<input name="loa_date" type="date" defaultValue={item.loa_date || ""} required /><small>{item.loa_date ? "✓ Extracted from LOA" : "⚠ Review required — No authoritative LOA issue date was identified in the source."}</small></label><label>Completion Period<input name="completion_period" defaultValue={item.completion_period || ""} /><small>{item.completion_period || "No contractual completion period was identified."}</small></label><label>Completion Date<input name="completion_date" type="date" defaultValue={item.completion_date || ""} /><small>{item.completion_date_provenance === "DERIVED" ? `✓ Calculated from LOA date + ${item.completion_period}` : item.completion_date_provenance === "SOURCE_EXTRACTED" ? "✓ Explicitly stated in LOA" : item.completion_period && !item.loa_date ? "⚠ Waiting for LOA Issued Date" : "⚠ No derivable contractual completion date identified"}</small></label><label>Contract Value<input name="contract_value" type="number" step="0.01" defaultValue={item.contract_value || ""} required /></label><input name="issuing_party_id" type="hidden" value={item.issuing_party_id || ""} /></div></section>
      <section className="wcdms-card railway-details"><h2>Railway Details</h2><dl className="settings-summary"><div><dt>Railway Zone</dt><dd>{zoneName}<br /><small>{item.railway_zone_id ? "✓ Matched with Railway Zone Master" : "⚠ Not found uniquely in Railway Zone Master"}</small></dd></div><div><dt>Railway Division</dt><dd>{divisionName}<br /><small>{item.railway_division_id ? "✓ Matched with Railway Division Master" : "⚠ Not found uniquely in the selected Railway Zone"}</small></dd></div></dl>{!item.railway_zone_id && <label>Resolve Railway Zone<select name="railway_zone_id" required><option value="">Select Railway Zone</option>{(masters["railway-zones"] ?? []).map((record) => <option key={record.id} value={record.id}>{display(record)}</option>)}</select></label>}{item.railway_zone_id && <input name="railway_zone_id" type="hidden" value={item.railway_zone_id} />}{!item.railway_division_id && <label>Resolve Railway Division<select name="railway_division_id" required><option value="">Select Railway Division</option>{(masters["railway-divisions"] ?? []).filter((record) => !item.railway_zone_id || record.data.zone_id === item.railway_zone_id).map((record) => <option key={record.id} value={record.id}>{display(record)}</option>)}</select></label>}{item.railway_division_id && <input name="railway_division_id" type="hidden" value={item.railway_division_id} />}{<div className="authority-details"><h3>Authority Details</h3><label>Consignee master mapping (optional)<select name="authority_id" defaultValue={item.authority_id || ""}><option value="">Select an existing Railway Authority if needed</option>{(masters["railway-authorities"] ?? []).filter((record) => !item.railway_division_id || record.data.division_id === item.railway_division_id).map((record) => <option key={record.id} value={record.id}>{display(record)}</option>)}</select></label>{["ISSUING_AUTHORITY", "CONSIGNEE", "EXECUTION_AUTHORITY"].map((role) => <div key={role}><strong>{role.replaceAll("_", " ").toLowerCase()}</strong>{authorityByRole(role).length ? authorityByRole(role).map((candidate, index) => <p key={`${candidate.text}-${index}`}>{candidate.text}<br /><small>✓ Extracted · Source: {candidate.source}<br />{candidate.master_status === "MATCHED" ? "✓ Matched with Railway Authority Master" : candidate.master_status === "AMBIGUOUS" ? "⚠ Multiple compatible masters — owner selection required" : "Master mapping: Not configured (optional)"}{candidate.master_detail && <><br />{candidate.master_detail}</>}</small></p>) : <p>Not explicitly identified in LOA</p>}</div>)}<Link className="button-secondary"
  to={`/master-data?type=railway-authorities&returnTo=${encodeURIComponent(`/loa-imports/${item.id}`)}`}
>
  Open Railway Authority Master</Link></div>}<button type="button" className="button-secondary" onClick={() => setShowExtractionDetails((value) => !value)}>View Extraction Details</button>{showExtractionDetails && <dl className="settings-summary"><div><dt>LOA date audit</dt><dd>{item.loa_date_provenance || "Needs review"}<br /><small>{item.loa_date_source || "No authoritative source identified"}</small></dd></div><div><dt>Completion date audit</dt><dd>{item.completion_date_provenance || "Needs review"}</dd></div></dl>}</section>
      {unmappedAuthority && item.railway_division_id && <div className="import-actions"><Link className="button-secondary" to={`/master-data?type=railway-authorities&division_id=${item.railway_division_id}&suggestion=${encodeURIComponent(unmappedAuthority.text)}&returnTo=${encodeURIComponent(`/loa-imports/${item.id}`)}`}>Add extracted designation to Railway Master</Link><button className="button-secondary" type="button" disabled={refreshingMasters} onClick={() => void refreshMasterMatches()}>{refreshingMasters ? "Refreshing Railway Master Matches…" : "Refresh Railway Master Matches"}</button></div>}
      <section className="wcdms-card"><h2>Work Description</h2><textarea name="work_description" defaultValue={item.work_description || ""} required /></section>
      <h2 className="sr-only">BOQ / Item Schedule</h2><p className="boq-view-mode" role="status">{onlyUnresolved ? `Unresolved BOQ Items — ${unresolved.length}` : "BOQ Items — All"}</p>
      <section className="wcdms-card import-boq"><header><div><h2>Extraction Reconciliation</h2><p>{complete ? `✓ Complete — ${metric(reconciliation, "extracted_successfully")}/${metric(reconciliation, "source_rows_detected")} source items reconciled` : `⚠ Review required — ${unresolved.length} source item(s) unresolved`}</p></div><div className="import-actions"><button type="button" className="button-secondary" onClick={() => { setOnlyUnresolved(true); setShowBoq(true); }}>Review Missing / Unresolved Items</button><button type="button" className="button-secondary" onClick={() => setShowBoq((v) => !v)}>View BOQ Items</button><button type="button" className="button-secondary" onClick={() => void openOriginalLoa(token!, item.id, item.original_filename)}>View Original LOA</button></div></header><dl className="settings-summary">{[["Pages processed", "pages_processed"], ["Native-text pages", "native_text_pages"], ["OCR pages", "ocr_pages"], ["Schedules detected", "schedules_detected"], ["Schedules covered", "schedule_sections_accounted_for"], ["Item groups detected", "item_groups_detected"], ["Source rows detected", "source_rows_detected"], ["Structured rows", "extracted_successfully"], ["Needs review", "needs_review"], ["Ignored / non-BOQ", "explicitly_ignored"], ["Unparsed / rejected", "unparsed_rejected"], ["Total discrepancies", "total_discrepancies"]].map(([label, key]) => <div key={key}><dt>{label}</dt><dd>{metric(reconciliation, key)}</dd></div>)}</dl>
      {showBoq && <div className="table-container"><table><thead><tr><th>Schedule</th><th>Sn. No.</th><th>Description</th><th>UOM</th><th>Quantity</th><th>Rate</th><th>Amount</th><th>Outcome</th></tr></thead><tbody>{visibleLines.map((line) => { const context = groupContext.get(line.group_id || ""); return <tr key={line.id}><td>{context?.schedule || "Unresolved schedule"}<br /><small>{context?.group || "Group unresolved"}<br />Pages {line.source_page_start ?? line.source_page ?? "—"}{line.source_page_end && line.source_page_end !== line.source_page_start ? `–${line.source_page_end}` : ""}</small></td><td><label>Reviewed Sn. No.<input value={line.source_serial || ""} placeholder="Needs review" onChange={(e) => updateLine(line.id, "source_serial", e.target.value)} /></label><small>{line.extraction_method || item.extraction_method || "—"}{line.extraction_confidence ? ` · ${Math.round(Number(line.extraction_confidence) * 100)}% confidence` : ""}</small></td><td><label>Reviewed description<textarea value={line.description || ""} onChange={(e) => updateLine(line.id, "description", e.target.value)} /></label>{line.description_raw && <details><summary>Raw reconstructed description</summary><pre>{line.description_raw}</pre></details>}{line.source_raw_text && <details><summary>Raw source evidence</summary><pre>{line.source_raw_text}</pre></details>}</td><td><select value={line.unit_id || ""} onChange={(e) => updateLine(line.id, "unit_id", e.target.value)}><option value="">{line.uom_raw || line.unit_text || "Needs review"}</option>{(masters.units ?? []).map((r) => <option key={r.id} value={r.id}>{display(r)}</option>)}</select>{line.uom_normalized && <small>Interpreted: {line.uom_normalized}</small>}</td><td><input type="number" step="0.0001" value={line.quantity || ""} onChange={(e) => updateLine(line.id, "quantity", e.target.value)} /></td><td><input type="number" step="0.01" value={line.rate || ""} onChange={(e) => updateLine(line.id, "rate", e.target.value)} /></td><td>{line.amount || "—"}</td><td><select value={line.extraction_outcome} onChange={(e) => updateLine(line.id, "extraction_outcome", e.target.value)}><option value="EXTRACTED">Extracted</option><option value="NEEDS_REVIEW">Needs review</option><option value="REJECTED_WITH_REASON">Rejected with reason</option><option value="EXPLICITLY_IGNORED_BY_OWNER">Mark Not a BOQ Item</option></select>{(line.extraction_issues?.length ? line.extraction_issues : line.extraction_issue ? [line.extraction_issue] : []).map((issue) => <small key={issue}>⚠ {issue}</small>)}</td></tr>; })}</tbody></table></div>}</section>
      <section className="wcdms-card"><h2>Validation / Warnings</h2>{item.extraction_warnings.length ? <ul>{item.extraction_warnings.map((warning) => <li key={warning}>⚠ {warning}</li>)}</ul> : <p>✓ No parser warnings.</p>}</section>{editable && <div className="import-actions"><button className="button-primary">Save Review Draft</button></div>}</form>
    {editable && <form className="wcdms-card import-approval" onSubmit={approve}><h2>Required Before Registration</h2><ul className="required-actions"><li>{item.railway_zone_id ? "✓ Railway Zone resolved" : "⚠ Railway Zone requires owner selection"}</li><li>{item.railway_division_id ? "✓ Railway Division resolved" : "⚠ Railway Division requires owner selection"}</li><li>{item.loa_date ? "✓ LOA Issued Date resolved" : "⚠ LOA Issued Date requires review"}</li><li>{complete ? `✓ ${metric(reconciliation, "extracted_successfully")}/${metric(reconciliation, "source_rows_detected")} BOQ items reconciled` : "⚠ BOQ reconciliation requires review"}</li></ul>{projectMode === "new" && <div className="settings-form"><label>New Project code<input name="new_project_code" required /></label><label>New Project name<input name="new_project_name" defaultValue={item.work_description || ""} required /></label></div>}{item.duplicate_candidates.length > 0 && <label className="check-field"><input name="confirm_duplicate" type="checkbox" /> I reviewed the possible duplicate and intend to proceed.</label>}{approvalBlocked && <div className="settings-feedback error"><strong>Cannot register LOA yet:</strong><ul>{requiredActions.map((reason) => <li key={reason}>{reason}</li>)}</ul></div>}<div className="import-actions"><button className="button-secondary" type="button" onClick={() => void cancelLoaImport(token!, item.id).then(load)}>Cancel Import</button><button className="button-primary" disabled={approvalBlocked}>Approve &amp; Create LOA</button></div></form>}{item.loa_id && <Link className="button-primary" to={`/loas/${item.loa_id}`}>Open Authoritative LOA</Link>}
  </section>;
}
