import { FormEvent, useCallback, useEffect, useState } from "react";
import { createPayment, eligibleInvoices, allocatePayment, listPayments, paymentAction, type EligibleInvoice, type Payment } from "../api/payments";
import { listMasterData, type MasterRecord } from "../api/masterData";
import { useAuth } from "../auth/AuthContext";

const label = (x: MasterRecord) => String(x.data.trade_name ?? x.data.legal_name ?? x.data.bank_name ?? x.data.name ?? x.id);
export function PaymentsPage() {
  const { token, user } = useAuth(); const [payments, setPayments] = useState<Payment[]>([]); const [parties, setParties] = useState<MasterRecord[]>([]); const [organizations, setOrganizations] = useState<MasterRecord[]>([]); const [banks, setBanks] = useState<MasterRecord[]>([]); const [selected, setSelected] = useState(""); const [eligible, setEligible] = useState<EligibleInvoice[]>([]);
  const load = useCallback(async () => { if (!token) return; const [p, partiesResult, orgResult, bankResult] = await Promise.all([listPayments(token), listMasterData(token, "parties"), listMasterData(token, "organizations"), listMasterData(token, "bank-accounts")]); setPayments(p); setParties(partiesResult.items.filter(x => Array.isArray(x.data.roles) && x.data.roles.includes("CUSTOMER"))); setOrganizations(orgResult.items); setBanks(bankResult.items); }, [token]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (token && selected) void eligibleInvoices(token, selected).then(setEligible); else setEligible([]); }, [token, selected]);
  async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!token) return; const f=e.currentTarget,d=new FormData(f); await createPayment(token,{receipt_date:d.get("date"),customer_party_id:d.get("customer"),organization_id:d.get("organization"),bank_account_id:d.get("bank")||undefined,payment_mode:d.get("mode"),transaction_reference:d.get("reference")||undefined,transaction_date:d.get("transaction_date")||undefined,amount_received:d.get("amount"),currency:"INR",notes:d.get("notes")||undefined}); f.reset(); await load(); }
  async function allocate(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!token || !selected) return; const d=new FormData(e.currentTarget); await allocatePayment(token,selected,{tax_invoice_id:d.get("invoice"),allocated_amount:d.get("amount"),allocation_date:d.get("date")}); setSelected(""); await load(); }
  const superAdmin=user?.roles.some(r=>r.name==="SUPER-ADMIN");
  return <section className="space-y-8"><div><p className="text-sm tracking-[.2em] text-cyan-400">PHASE 14</p><h1 className="text-3xl font-semibold">Customer Payments</h1></div><form onSubmit={create} className="grid gap-2 rounded border p-4 md:grid-cols-3"><h2 className="text-xl md:col-span-3">Record receipt</h2><input name="date" type="date" aria-label="Receipt date" required/><select name="customer" aria-label="Customer" required><option value="">Customer</option>{parties.map(x=><option key={x.id} value={x.id}>{label(x)}</option>)}</select><select name="organization" aria-label="Organization" required><option value="">Organization</option>{organizations.map(x=><option key={x.id} value={x.id}>{label(x)}</option>)}</select><select name="bank" aria-label="Bank account"><option value="">No bank</option>{banks.map(x=><option key={x.id} value={x.id}>{label(x)}</option>)}</select><select name="mode" aria-label="Payment mode" required><option>NEFT</option><option>RTGS</option><option>IMPS</option><option>UPI</option><option>CHEQUE</option><option>CASH</option><option>OTHER</option></select><input name="reference" placeholder="Transaction reference"/><input name="transaction_date" type="date" aria-label="Transaction date"/><input name="amount" type="number" step="0.01" min="0.01" placeholder="Amount received" required/><input name="notes" placeholder="Notes"/><button>Record draft receipt</button></form><div><h2 className="text-xl">Payment register</h2>{payments.map(x=><article key={x.id} className="rounded border p-3"><strong>{x.receipt_number}</strong> — {x.customer_snapshot.trade_name||x.customer_snapshot.legal_name} — ₹{x.amount_received} — {x.status} — unallocated ₹{x.unallocated_amount}{x.status==="DRAFT"&&<button className="ml-3" onClick={()=>setSelected(x.id)}>Allocate</button>}{superAdmin&&x.status==="DRAFT"&&<><button className="ml-3" onClick={()=>void paymentAction(token!,x.id,"CONFIRM","Bank receipt verified").then(load)}>Confirm</button><button className="ml-3" onClick={()=>void paymentAction(token!,x.id,"CANCEL","Cancelled by finance").then(load)}>Cancel</button></>}{superAdmin&&x.status==="CONFIRMED"&&<button className="ml-3" onClick={()=>void paymentAction(token!,x.id,"REVERSE","Reversed by finance").then(load)}>Reverse</button>}</article>)}</div>{selected&&<form onSubmit={allocate} className="grid gap-2 rounded border p-4 md:grid-cols-3"><h2 className="text-xl md:col-span-3">Allocate receipt</h2><select name="invoice" aria-label="Eligible invoice" required><option value="">Invoice</option>{eligible.map(x=><option key={x.tax_invoice_id} value={x.tax_invoice_id}>{x.invoice_number} — outstanding ₹{x.outstanding_amount}</option>)}</select><input name="amount" type="number" step="0.01" min="0.01" placeholder="Allocation amount" required/><input name="date" type="date" required/><button>Save allocation</button></form>}</section>;
}
