import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { listLoas, listProjects, type Loa, type Project } from "../api/contracts";
import { ApiError } from "../api/client";
import { listMasterData, listTermsVersions, type MasterRecord, type TermsVersion } from "../api/masterData";
import { createPurchaseOrder, createRequirement, getCommitments, listPurchaseOrders, listRequirements, type Commitment, type PurchaseOrder, type Requirement } from "../api/procurement";
import { useAuth } from "../auth/AuthContext";

const label=(r:MasterRecord)=>String(r.data.legal_name??r.data.name??r.data.label??r.id);
export function ProcurementPage(){
 const {token}=useAuth();const [requirements,setRequirements]=useState<Requirement[]>([]);const [orders,setOrders]=useState<PurchaseOrder[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [loas,setLoas]=useState<Loa[]>([]);const [vendors,setVendors]=useState<MasterRecord[]>([]);const [organizations,setOrganizations]=useState<MasterRecord[]>([]);const [addresses,setAddresses]=useState<MasterRecord[]>([]);const [units,setUnits]=useState<MasterRecord[]>([]);const [paymentTerms,setPaymentTerms]=useState<MasterRecord[]>([]);const [termsVersions,setTermsVersions]=useState<TermsVersion[]>([]);const [vendorSearch,setVendorSearch]=useState("");const [selectedLoa,setSelectedLoa]=useState("");const [commitments,setCommitments]=useState<Commitment[]>([]);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!token)return;try{const [r,p,pr,l,v,o,a,u,t,pt]=await Promise.all([listRequirements(token),listPurchaseOrders(token),listProjects(token),listLoas(token),listMasterData(token,"parties"),listMasterData(token,"organizations"),listMasterData(token,"organization-addresses"),listMasterData(token,"units"),listMasterData(token,"terms-condition-sets"),listMasterData(token,"payment-terms")]);setRequirements(r);setOrders(p);setProjects(pr);setLoas(l);setVendors(v.items.filter(x=>(x.data.roles as string[]|undefined)?.includes("VENDOR")));setOrganizations(o.items);setAddresses(a.items);setUnits(u.items);setPaymentTerms(pt.items);const sets=t.items.filter(x=>["PURCHASE","GENERAL"].includes(String(x.data.context)));setTermsVersions((await Promise.all(sets.map(x=>listTermsVersions(token,x.id)))).flat());}catch(e){setError(e instanceof ApiError?e.message:"Unable to load procurement.");}},[token]);useEffect(()=>{void load();},[load]);useEffect(()=>{if(token&&selectedLoa)void getCommitments(token,selectedLoa).then(setCommitments);else setCommitments([]);},[token,selectedLoa]);const filteredVendors=useMemo(()=>vendors.filter(v=>label(v).toLowerCase().includes(vendorSearch.toLowerCase())),[vendors,vendorSearch]);
 async function addRequirement(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;const f=e.currentTarget,d=new FormData(f);try{await createRequirement(token,{project_id:d.get("project_id"),loa_id:d.get("loa_id")||undefined,requirement_date:d.get("date"),lines:[{description:d.get("description"),unit_id:d.get("unit_id"),required_quantity:d.get("quantity")}]});f.reset();await load();}catch(c){setError(c instanceof ApiError?c.message:"Unable to create requirement.");}}
 async function addPo(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;const f=e.currentTarget,d=new FormData(f),[origin,id]=String(d.get("contract_source")??"").split(":");const source=origin==="ORIGINAL_LOA"?{loa_item_id:id}:origin==="VARIATION"?{variation_line_id:id}:{};const intra=d.get("tax_mode")==="INTRA_STATE";try{await createPurchaseOrder(token,{po_date:d.get("date"),vendor_party_id:d.get("vendor_id"),project_id:d.get("project_id"),loa_id:d.get("loa_id")||undefined,organization_id:d.get("organization_id"),billing_organization_address_id:d.get("billing_id"),ship_to_organization_address_id:d.get("shipping_id"),payment_term_id:d.get("payment_term_id")||undefined,terms_version_id:d.get("terms_version_id")||undefined,tax_mode:d.get("tax_mode"),lines:[{description:d.get("description"),unit_id:d.get("unit_id"),ordered_quantity:d.get("quantity"),unit_rate:d.get("rate"),cgst_percent:intra?"9":"0",sgst_percent:intra?"9":"0",igst_percent:intra?"0":"18",...source}]});f.reset();setSelectedLoa("");await load();}catch(c){setError(c instanceof ApiError?c.message:"Unable to create PO.");}}
 return <section className="space-y-8"><div><p className="text-sm tracking-[.2em] text-cyan-400">PHASE 05</p><h1 className="text-3xl font-semibold">Procurement & Purchase Orders</h1></div>{error&&<p role="alert">{error}</p>}
 <form onSubmit={addRequirement} className="grid gap-2 rounded border p-4 md:grid-cols-3"><h2 className="text-xl md:col-span-3">New procurement requirement</h2><select name="project_id" aria-label="Requirement project" required>{projects.map(x=><option value={x.id} key={x.id}>{x.code} — {x.name}</option>)}</select><select name="loa_id" aria-label="Requirement LOA"><option value="">No LOA</option>{loas.map(x=><option value={x.id} key={x.id}>{x.loa_number}</option>)}</select><input name="date" type="date" required/><input name="description" placeholder="Description" required/><select name="unit_id" aria-label="Requirement unit" required>{units.map(x=><option value={x.id} key={x.id}>{label(x)}</option>)}</select><input name="quantity" type="number" step="0.0001" placeholder="Quantity" required/><button>Create requirement</button></form>
 <div><h2 className="text-xl">Requirements</h2>{requirements.map(x=><article key={x.id}><Link to={`/procurement-requirements/${x.id}`}>{x.requirement_number}</Link> — {x.status}</article>)}</div>
 <form onSubmit={addPo} className="grid gap-2 rounded border p-4 md:grid-cols-3"><h2 className="text-xl md:col-span-3">New purchase order</h2><input aria-label="Search vendors" value={vendorSearch} onChange={e=>setVendorSearch(e.target.value)} placeholder="Search vendors"/><select name="vendor_id" aria-label="Vendor" required>{filteredVendors.map(x=><option value={x.id} key={x.id}>{label(x)}</option>)}</select><select name="project_id" aria-label="PO project" required>{projects.map(x=><option value={x.id} key={x.id}>{x.code} — {x.name}</option>)}</select><select name="loa_id" aria-label="PO LOA" value={selectedLoa} onChange={e=>setSelectedLoa(e.target.value)}><option value="">No LOA</option>{loas.map(x=><option value={x.id} key={x.id}>{x.loa_number}</option>)}</select><select name="contract_source" aria-label="Contractual item"><option value="">Unlinked line</option>{commitments.map(x=><option key={x.contractual_item_id} value={`${x.origin}:${x.contractual_item_id}`}>{x.origin}: approved {x.approved_quantity}, committed {x.committed_quantity}, remaining {x.remaining_quantity}</option>)}</select><select name="organization_id" aria-label="Buyer" required>{organizations.map(x=><option value={x.id} key={x.id}>{label(x)}</option>)}</select><select name="billing_id" aria-label="Billing address" required>{addresses.filter(x=>x.data.address_type==="BILL_TO").map(x=><option value={x.id} key={x.id}>{label(x)}</option>)}</select><select name="shipping_id" aria-label="Ship-to address" required>{addresses.filter(x=>x.data.address_type==="SHIP_TO").map(x=><option value={x.id} key={x.id}>{label(x)}</option>)}</select><select name="payment_term_id" aria-label="Payment terms"><option value="">No payment terms</option>{paymentTerms.map(x=><option value={x.id} key={x.id}>{label(x)}</option>)}</select><select name="terms_version_id" aria-label="Terms version"><option value="">No T&amp;C version</option>{termsVersions.map(x=><option value={x.id} key={x.id}>Version {x.version}</option>)}</select><select name="tax_mode" aria-label="Tax mode"><option>INTRA_STATE</option><option>INTER_STATE</option></select><input name="date" type="date" required/><input name="description" placeholder="Line description" required/><select name="unit_id" aria-label="PO unit" required>{units.map(x=><option value={x.id} key={x.id}>{label(x)}</option>)}</select><input name="quantity" type="number" step="0.0001" placeholder="Quantity" required/><input name="rate" type="number" step="0.01" placeholder="Vendor rate" required/><button>Create PO</button></form>
 <div><h2 className="text-xl">Purchase orders</h2>{orders.map(x=><article key={x.id}><Link to={`/purchase-orders/${x.id}`}>{x.po_number}</Link> — {x.status} — ₹{x.grand_total}</article>)}</div></section>;
}
