import { useEffect,useMemo,useState } from "react";
import { exportReport } from "../api/reporting";
import { listReceivables,type Receivable } from "../api/payments";
import { useAuth } from "../auth/AuthContext";
import { Icon } from "../components/Icon";

const money=(value:string)=>`₹${Number(value).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function ReceivablesPage(){const {token}=useAuth();const [rows,setRows]=useState<Receivable[]>([]);const [from,setFrom]=useState("");const [to,setTo]=useState("");const [customer,setCustomer]=useState("");const [status,setStatus]=useState("");const [applied,setApplied]=useState({from:"",to:"",customer:"",status:""});useEffect(()=>{if(token)void listReceivables(token).then(setRows);},[token]);const customers=useMemo(()=>[...new Set(rows.map(x=>x.customer_name))].sort(),[rows]);const visible=rows.filter(x=>(!applied.from||!x.due_date||x.due_date>=applied.from)&&(!applied.to||!x.due_date||x.due_date<=applied.to)&&(!applied.customer||x.customer_name===applied.customer)&&(!applied.status||x.payment_status===applied.status));const reportQuery=()=>{const q=new URLSearchParams();if(applied.status)q.set("status",applied.status);return q.toString();};return <section className="receivables-page page-stack">
  <header className="page-heading"><p>PHASE 14</p><h1>Receivables</h1><span>Derived from issued Tax Invoices and confirmed customer-payment allocations.</span></header>
  <section className="wcdms-card receivable-filters" aria-label="Receivable filters"><label>From Date<input aria-label="From date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To Date<input aria-label="To date" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Customer<select aria-label="Customer" value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">All Customers</option>{customers.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Statuses</option>{[...new Set(rows.map(x=>x.payment_status))].map(x=><option key={x}>{x}</option>)}</select></label><button className="button-primary" onClick={()=>setApplied({from,to,customer,status})}>Apply Filters</button><button className="button-secondary" onClick={()=>token&&void exportReport(token,"receivables",reportQuery())}>Export Excel</button></section>
  <section className="wcdms-card register-card"><h2><Icon name="document"/>Receivables Summary</h2><div className="table-container"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Total</th><th>Received</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{visible.map(x=><tr key={x.tax_invoice_id}><td>{x.invoice_number}</td><td>{x.customer_name}</td><td>{money(x.invoice_total)}</td><td>{money(x.received_amount)}</td><td>{money(x.outstanding_amount)}</td><td><span className={`status-badge ${x.days_overdue>0?"overdue":x.payment_status.toLowerCase()}`}>{x.payment_status}{x.days_overdue>0?` (${x.days_overdue} days)`:""}</span></td></tr>)}</tbody></table>{visible.length===0&&<div className="register-empty"><span className="empty-icon"><Icon name="document"/></span><strong>No receivable records found.</strong><p>Try adjusting your filters or check back later.</p></div>}</div><footer className="register-footer"><span>Showing {visible.length===0?0:1} to {visible.length} of {visible.length} entries</span><div><button disabled>Previous</button><button disabled>Next</button></div></footer></section>
</section>}
