import { useCallback,useEffect,useState } from "react";
import { useSearchParams } from "react-router-dom";
import { exportReport,getReport } from "../api/reporting";
import { useAuth } from "../auth/AuthContext";
import { Icon } from "../components/Icon";

const groups={"PROJECT / CONTRACT":["projects","variations"],PROCUREMENT:["requirements","purchase-orders"],LOGISTICS:["receipts","challans"],ASSETS:["assets"],BILLING:["proforma-invoices","tax-invoices"],FINANCE:["receivables","payments"],ATTENTION:["alerts"]};
export function ReportsPage(){const {token,user}=useAuth();const [params,setParams]=useSearchParams();const report=params.get("report")??"projects";const [rows,setRows]=useState<Record<string,unknown>[]>([]);const [offset,setOffset]=useState(0);const superAdmin=user?.roles.some(r=>r.name==="SUPER-ADMIN");const query=()=>{const q=new URLSearchParams();for(const key of ["date_from","date_to","financial_year","status"]){const value=(document.querySelector(`[name=${key}]`) as HTMLInputElement|null)?.value;if(value)q.set(key,value);}q.set("offset",String(offset));q.set("limit","50");return q.toString();};const load=useCallback(async()=>{if(token)setRows(await getReport(token,report,`offset=${offset}&limit=50`));},[token,report,offset]);useEffect(()=>{void load();},[load]);async function filter(){if(token)setRows(await getReport(token,report,query()));}const headers=rows[0]?Object.keys(rows[0]):[];return <section className="reports-page page-stack">
  <header className="page-heading"><p>MANAGEMENT INFORMATION</p><h1>Reports</h1></header>
  <div className="report-groups">{Object.entries(groups).map(([group,names])=><section className="report-category" key={group}><h2>{group}</h2>{names.filter(name=>superAdmin||!["proforma-invoices","tax-invoices","receivables","payments"].includes(name)).map(name=><button className={name===report?"selected":""} key={name} onClick={()=>{setParams({report:name});setOffset(0);}}>{name.replaceAll("-"," ")}</button>)}</section>)}</div>
  <section className="wcdms-card report-filters" aria-label="Report filters"><input name="date_from" type="date" aria-label="From date"/><input name="date_to" type="date" aria-label="To date"/><input name="financial_year" placeholder="Financial year 2026-27"/><input name="status" placeholder="Status"/><button className="button-primary" onClick={()=>void filter()}>Apply filters</button><button className="button-secondary" onClick={()=>token&&void exportReport(token,report,query())}>Export Excel</button></section>
  <section className="wcdms-card report-results"><h2>{report.replaceAll("-"," ")}</h2>{rows.length===0?<div className="contained-empty"><Icon name="report"/><p>No records match the selected filters.</p></div>:<div className="table-container"><table><thead><tr>{headers.map(h=><th key={h}>{h.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id??index)}>{headers.map(h=><td key={h}>{typeof row[h]==="object"?JSON.stringify(row[h]):String(row[h]??"")}</td>)}</tr>)}</tbody></table></div>}</section>
  <nav className="pagination" aria-label="Report results pages"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><span>Page {Math.floor(offset/50)+1}</span><button disabled={rows.length<50} onClick={()=>setOffset(offset+50)}>Next</button></nav>
</section>}
